Kmeans
campbio/musicatk pull request #15
Opened 2020-11-25 03:32 UTC by BioTong

Add functions related to k-means clustering, unit test script, and description files.

2020-11-25 03:59 UTC, achevali commented on R/kmeans.R
> +Kmeans <- function(result, ...){
Just keep it lower case ```kmeans```

2020-11-25 05:18 UTC, achevali requested changes

2020-12-02 17:45 UTC, BioTong commented on R/kmeans.R
> +      if(ncol(result@musica@sample_annotations) == 1) {stop("Sample annotation not found.")}
I find that the sample_annotations data.frame in the musica object has one and only one column of sample IDs initially, so I guess checking the number of columns can tell you if sample annotation is added?

2020-12-02 18:06 UTC, achevali commented on R/kmeans.R
> +      if(ncol(result@musica@sample_annotations) == 1) {stop("Sample annotation not found.")}
You should have annotation as a parameter defaulting to NULL, and if group == "annotation", check that ```annotation %in% names(samp_annot(result))```

2020-12-12 18:41 UTC, achevali commented
Push any updates you've made to the code so I can review them.

2020-12-15 01:49 UTC, closed without merging