add code to sig_compare function to find best match
campbio/musicatk pull request #57
Opened 2023-05-12 22:41 UTC by Gtnick1241

add code to sig_compare function to find best match.

2023-05-15 17:57 UTC, joshua-d-campbell requested changes
Nice job overall! A few more things need to be tweaked.

2023-05-15 17:57 UTC, joshua-d-campbell commented on R/compare_results.R
>                             ]
You should try to keep the brackets "]" on the same line. You can automatically format the code in Rstudio.

2023-05-15 17:57 UTC, joshua-d-campbell commented on R/compare_results.R
> +  split_comparison <- split(comparison, comparison$x_sig_name)
We still want to be able to do the old way of plotting as well. Could you add a parameter to this function like this:

`type = c("best", "threshold")`

If "best" is selected, then you can run your new code. If "threshold" is selected, you can run the old way using the threshold parameter. Note that you will also have to add this parameter to the other compare-* functions

2023-05-15 17:57 UTC, joshua-d-campbell commented on R/compare_results.R
> +  split_comparison <- split(comparison, comparison$x_sig_name)
Also, make sure to document the new parameter!

2023-05-16 23:09 UTC, Gtnick1241 commented
I had already committed a new code.

2023-07-19 04:40 UTC, Gtnick1241 commented
I am sorry to commit many irrelevant data. My major code is in main_class and standard_table file.

2024-01-09 17:30 UTC, closed without merging